spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: badiro12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # optioanal
    properties:
      hibernate:
        format_sql: true
    database: postgresql


#  mail:
#    host: localhost
#    port: 1025
#    username: hasan
#    password: hasan
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enable: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
  mail:
    host: ${EMAIL_HOST_NAME}
    port: 587
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days --> not used
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://192.168.0.227:8088/,http://localhost:8088/,http://localhost:4200,http://192.168.0.227:8080
  file:
    upload:
      photos-output-path: ./app/uploads
server:
  port: 8088